### ISSUE TITLE
Követelmény specifikáció feltöltése

### ISSUE THREAD

**Issue by dbzmonty** [dbzmonty/PTI_FOSZ_Robotika_Android_RFT_Beadando#1]
Követelmény specifikáció feltöltése
---------------------------------------

**Felelősök:** az egész csapat
**Határidő:** 2017.10.09.

Bíró Patrik - fejléc
Dobozi András - műszaki leírás
Eged Zsolt - kezelői felületek
Balázs Gergő - android alkalmazás menüpontok

**Comment by biropatrik** [comment]
A követelmény specifikációt szükséges kiegészíteni.

**Comment by biropatrik** [comment]
Elkezdtem kiegészíteni, ekkor :  2017.12.14. 19:40

**Comment by biropatrik** [comment]
Befejeztem a kiegészítést, ráfordított idő ~60 perc. 
Befejezés időpontja: 2017.12.14. 20:45

**Comment by biropatrik** [comment]
6b8200d-es commit.
