### ISSUE TITLE
Tesztelési jegyzőkönyv felvétele

### ISSUE THREAD

**Issue by sontqq** [dbzmonty/PTI_FOSZ_Robotika_Android_RFT_Beadando#19]
A tesztelési jegyzőkönyvet kéne megírni.

**Comment by sontqq** [comment]
Valami hasonlót kéne alkotni szerintem mint amit egyszer Tajti tanár úrral csináltunk órán azt az Androidos app tesztelős táblázatot nem? Másra nem nagyon tudok gondolni.

**Comment by dbzmonty** [comment]
Tesztelés folyamatban, Általános funkcionális teszt elkészült: 2017.12.10.
Ráfordított idő 1h

**Comment by dbzmonty** [comment]
Tesztelés folyamatban, Szélsőérték funkcionális teszt elkészült: 2017.12.11.
Ráfordított idő 1h

**Comment by dbzmonty** [comment]
Teljesítményteszt elkészült, nagy mennyiségű bemenő adattal: 2017.12.12.
Hibátlan működés, mérnöki csoda.
Ráfordított idő 1h

**Comment by dbzmonty** [comment]
Tesztelés lezárult, jegyzőkönyv kitöltése folyamatban.

**Comment by dbzmonty** [comment]
Tesztelési jegyzőkönyv elkészült, feltöltve.  Ráfordított idő 5h
