### ISSUE TITLE
Android: világítás visszajelzés

### ISSUE THREAD

**Issue by sontqq** [dbzmonty/PTI_FOSZ_Robotika_Android_RFT_Beadando#34]
Azt kéne megoldani, hogy az Android app mutassa a kinti - benti világítás állapotát, úgy ahogy a riasztónál.
Becsült fejlesztési idő: ~2 óra

**Comment by dbzmonty** [comment]
Megvalósítható ötlet lenne, de a rendelkezésre álló időbe már nem fér bele.
