### ISSUE TITLE
Android: Elérhető bluetooth eszközök listájának szépítése

### ISSUE THREAD

**Issue by sontqq** [dbzmonty/PTI_FOSZ_Robotika_Android_RFT_Beadando#35]
Kicsit módosítani kéne az activity kinézetén, hogy jobban illeszkedjen a főoldal dizájnjához.
Becsült fejlesztési idő: ~2 óra

**Comment by dbzmonty** [comment]
Elkészült a csatlakozás menü megújítása, immáron kétsoros az eszközlista, felül a BT eszköz neve, alul a MAC címe, így könnyebben kiválasztható az adott eszköz.
Ráfordított idő: ~2 óra
100% kész
commit: 76279a1
![screenshot_20171219-193908](https://user-images.githubusercontent.com/23232090/34173905-56055368-e4f7-11e7-9a55-d6255545965d.png)
