### ISSUE TITLE
Dokumentációk bővítése

### ISSUE THREAD

**Issue by Gr3gYx** [dbzmonty/PTI_FOSZ_Robotika_Android_RFT_Beadando#38]
Varázsoljunk még ~500 sort a dokumentációkba

**Comment by biropatrik** [comment]
Kibővítettem az ajánlatkérést, ez +50 sort jelent.

**Comment by biropatrik** [comment]
Ez a 6b8200d-es commit.

**Comment by Gr3gYx** [comment]
Bővítettem a Rendszertervet, 8121980-es commit, ez még +50 sor.
~45 perc

**Comment by Gr3gYx** [comment]
Bővítés, javítás, egyéb dogok (+100 sor)
Commitok: 7acae97, 48ca818, b62d568, c85794b
~2.5h

**Comment by Gr3gYx** [comment]
Eddig +200 sornál tartunk!

**Comment by Gr3gYx** [comment]
Jegyzőkönyvet hozzáadta SontQQ  (+60sor)
5744231-es commit
~5h

**Comment by dbzmonty** [comment]
Dokumentációk bővítése kész, összesen 275 sor jött össze.
Összes ráfordított idő: ~8h
